# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestCallhistorypage():
  def __init__(self, driver):
    self.driver = driver
    self.vars = {}

  def setup_method(self, method):
    pass  # Driver is already initialized in __init__

  def teardown_method(self, method):
    pass
  
  def test_callhistorypage(self):

    self.driver.get("https://app.uat.zudu.ai/")
    self.driver.set_window_size(1300, 736)
    self.driver.execute_script("document.body.style.zoom='0.5'")

    def click_element(by, value, sleep_time=1):
        from selenium.common.exceptions import TimeoutException
        try:
          element = WebDriverWait(self.driver, 10).until(
              EC.element_to_be_clickable((by, value))
          )
          self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", element)
          if element and element.is_displayed() and element.is_enabled():
            size = element.size
            if size['width'] > 0 and size['height'] > 0:
              print(element)
              try:
                element.click()
              except Exception as e:
                print(f"Click intercepted, trying JS click: {e}")
                #self.driver.execute_script("arguments[0].click();", element)
            else:
              print(f"Element found but has zero size: {element}")
          else:
            print(f"Element found but not interactable: {element}")
          time.sleep(5)
        except TimeoutException:
          print(f"Timeout: Element by {by} with value '{value}' not clickable after waiting.")
        except Exception as e:
          print(f'Error finding or clicking element by {by} with value "{value}": {e}')

    def send_keys(by,value,keys):
      try:
          input_elem = WebDriverWait(self.driver, 10).until(
              EC.element_to_be_clickable((by, value))
          )
          input_elem.send_keys(keys)
      except Exception as e:
          print(f"Could not find or interact with input: {e}")

    # Example for the first element
    click_element(By.CSS_SELECTOR, "li:nth-child(3) span", 1)
    time.sleep(10)
    click_element(By.CSS_SELECTOR, ".pl-\\[17px\\] path:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".pl-\\[17px\\] path:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(2) path:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(2) .lucide", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(3) .lucide", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(3) .lucide", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(4) path:nth-child(1)", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(4) .lucide", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(5) .lucide", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(5) .lucide", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(6) path:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".h-10:nth-child(6) path:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(1) > .ml-1", 1)
    click_element(By.ID, "agent_ff00f106-51a2-4fa7-b64a-3645a0f60539", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(2) > .ml-1", 1)
    click_element(By.CSS_SELECTOR, ".file\\3Atext-foreground", 1)
    send_keys(By.CSS_SELECTOR, ".file\\3Atext-foreground","123")
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-600", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(3) > .ml-1", 1)
    send_keys(By.CSS_SELECTOR, ".file\\3Atext-foreground","123")
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-600", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(4) > .ml-1", 1)
    click_element(By.ID, "Outbound", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(4) > .ml-1", 1)
    click_element(By.ID, "Inbound", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    send_keys(By.CSS_SELECTOR, ".file\\3Atext-foreground","1")
    click_element(By.CSS_SELECTOR, ".file\\3Atext-foreground", 1)
    click_element(By.CSS_SELECTOR, ".file\\3Atext-foreground", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(6) > .ml-1", 1)
    send_keys(By.CSS_SELECTOR, ".file\\3Atext-foreground","123")
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x > path:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(7) > .ml-1", 1)
    send_keys(By.CSS_SELECTOR, ".file\\3Atext-foreground","123")
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x > path:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(8) > .ml-1", 1)
    click_element(By.ID, "Positive", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x > path:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(8) > .ml-1", 1)
    click_element(By.ID, "Neutral", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(8) > .ml-1", 1)
    click_element(By.ID, "Negative", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(8) > .ml-1", 1)
    click_element(By.ID, "Unknown", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x > path:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(9) > .ml-1", 1)
    click_element(By.ID, "User Hangup", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-600", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(9) > .ml-1", 1)
    click_element(By.ID, "Agent Hangup", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(9) > .ml-1", 1)
    click_element(By.ID, "Call Transfer", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(9) > .ml-1", 1)
    click_element(By.ID, "Voicemail Reached", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-600", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(9) > .ml-1", 1)
    click_element(By.ID, "Inactivity", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(9) > .ml-1", 1)
    click_element(By.ID, "Machine Detected", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(10) > .ml-1", 1)
    click_element(By.ID, "Success", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-600", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(10) > .ml-1", 1)
    click_element(By.ID, "Unsuccess", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(11) > .ml-1", 1)
    click_element(By.CSS_SELECTOR, ".space-x-2:nth-child(1)", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".rounded", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(11) > .ml-1", 1)
    click_element(By.ID, "ongoing", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-gray-600", 1)
    click_element(By.CSS_SELECTOR, ".ml-1", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(11) > .ml-1", 1)
    click_element(By.ID, "error", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[15px\\]", 1)
    click_element(By.CSS_SELECTOR, ".space-y-1 > .w-full:nth-child(1)", 1)
    click_element(By.CSS_SELECTOR, ".bg-black", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[\\#0F0F10\\]", 1)
    click_element(By.CSS_SELECTOR, ".py-2:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[\\#0F0F10\\]", 1)
    click_element(By.CSS_SELECTOR, ".text-left:nth-child(3)", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[15px\\]", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[15px\\]", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(5)", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[15px\\]", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(6)", 1)
    click_element(By.CSS_SELECTOR, ".bottom-0", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[15px\\]", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(7)", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".gap-1\\.5", 1)
    click_element(By.CSS_SELECTOR, ".w-full:nth-child(8)", 1)
    click_element(By.CSS_SELECTOR, ".inline-flex:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".lucide-x", 1)
    click_element(By.CSS_SELECTOR, ".data-\\[state\\=selected\\]\\3A bg-muted:nth-child(2) .pl-\\[17px\\]", 1)
    click_element(By.CSS_SELECTOR, ".lucide-play", 1)
    click_element(By.CSS_SELECTOR, ".mt-2\\.5", 1)
    click_element(By.CSS_SELECTOR, ".py-0\\.5", 1)
    click_element(By.CSS_SELECTOR, ".font-\\[600\\]:nth-child(2)", 1)
    click_element(By.CSS_SELECTOR, ".text-\\[\\#1B1B1C\\]", 1)
    click_element(By.CSS_SELECTOR, ".font-\\[600\\]:nth-child(3)", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(1) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(2) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(3) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(4) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(5) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(6) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".font-\\[600\\]:nth-child(4)", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(1) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(2) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(3) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(4) > .py-5", 1)
    click_element(By.CSS_SELECTOR, ".hover\\3A bg-muted\\/50:nth-child(5) > .py-5", 1)
  
