# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestSettings():
  def __init__(self, driver):
    self.driver = driver
    self.vars = {}

  def setup_method(self, method):
    pass  

  def teardown_method(self, method):
    pass
  
  def test_settingspage(self):
    self.driver.get("https://app.uat.zudu.ai/")
    self.driver.set_window_size(1300, 736)
    self.driver.execute_script("document.body.style.zoom='0.5'")

    def click_element(by, value, sleep_time=1):
        from selenium.common.exceptions import TimeoutException
        try:
          element = WebDriverWait(self.driver, 10).until(
              EC.element_to_be_clickable((by, value))
          )
          self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", element)
          if element and element.is_displayed() and element.is_enabled():
            size = element.size
            if size['width'] > 0 and size['height'] > 0:
              print(element)
              try:
                element.click()
              except Exception as e:
                print(f"Click intercepted, trying JS click: {e}")
                #self.driver.execute_script("arguments[0].click();", element)
            else:
              print(f"Element found but has zero size: {element}")
          else:
            print(f"Element found but not interactable: {element}")
          #time.sleep(5)
        except TimeoutException:
          print(f"Timeout: Element by {by} with value '{value}' not clickable after waiting.")
        except Exception as e:
          print(f'Error finding or clicking element by {by} with value "{value}": {e}')

    def send_keys(by,value,keys):
      try:
          input_elem = WebDriverWait(self.driver, 10).until(
              EC.element_to_be_clickable((by, value))
          )
          input_elem.send_keys(keys)
      except Exception as e:
          print(f"Could not find or interact with input: {e}")

    self.driver.get("https://app.uat.zudu.ai/")
    self.driver.set_window_size(1300, 736)
    self.driver.execute_script("document.body.style.zoom='0.5'")

    # Click settings
    self.driver.find_element(By.XPATH, "//button[@id=\'radix-«R1srjb»\']/div[2]/span").click()
    click_element(By.CSS_SELECTOR, ".focus\\3A bg-accent:nth-child(3)")

    # Navigate
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(1)")
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(2)")
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(3)")
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(4)")
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(5)")  
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(6)")
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(7)")
    click_element(By.CSS_SELECTOR, ".mb-1:nth-child(8)")        