# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBatchcallpage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_batchcallpage(self):
    self.driver.get("https://app.uat.zudu.ai/")
    self.driver.set_window_size(1300, 736)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").send_keys("sar")
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Create Batch Call\')]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(2) > .border-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\!rounded-\\[6px\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\!rounded-\\[6px\\]").send_keys("+12344566778")
    self.driver.find_element(By.CSS_SELECTOR, ".\\!rounded-\\[6px\\]").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(3) > .border-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-blue-600").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-primary\\/90").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-primary\\/90").click()
  
