# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKnowledgebasepage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_knowledgebasepage(self):
    self.driver.get("https://app.uat.zudu.ai/")
    self.driver.set_window_size(1300, 736)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").send_keys("Knowledge base")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-6").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").click()
    self.driver.find_element(By.CSS_SELECTOR, ".file\\3Atext-foreground").send_keys("xyz123")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-6").click()
  
