# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignin():
  def __init__(self, driver):
    self.driver = driver
    self.vars = {}

  def setup_method(self, method):
    pass  # Driver is already initialized in __init__

  def teardown_method(self, method):
    pass
  
  def test_signin(self):
    # Test name: Sign in
    # Step # | name | target | value
    # 1 | open | /login | 
    self.driver.get("https://app.uat.zudu.ai/login")
    # 2 | setWindowSize | 602x743 | 
    #self.driver.set_window_size(602, 743)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 7 | type | id=email | admin@example.com
    self.driver.find_element(By.ID, "email").send_keys("admin@example.com")
    # 8 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 9 | type | id=password | admin123
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    # 10 | click | css=.inline-flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
  
