# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPhonenumberspage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_phonenumberspage(self):
    self.driver.get("https://app.uat.zudu.ai/")
    self.driver.set_window_size(1300, 736)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border-t:nth-child(1) > .pl-6:nth-child(1) > .text-\\[\\#0F0F10\\]").click()
  
